### ISSUE TITLE
Missing com.vaadin.book.examples.Description

### ISSUE THREAD

**Issue by edoyle** [vaadin/book-examples#1]
It seems that the source file for com.vaadin.book.examples.Description might not have been committed.

**Comment by Triebabfuhr** [comment]
Me experienced the same: 

cannot compile Vaadin book examples in Eclipse due to the missing com.vaadin.book.examples.Description 

It's missing in several sourcefiles, e.g. BookExample.java, CalendarExample.java, DateFieldExample.java, TableEditingExample.java, ExpandRatioExample.java

Would be very kind if you could upload the missing file.

**Comment by magi42** [comment]
This was fixed in [7e449729e62db1b682e8aa0485f616698bfeedcd] and is there now at https://github.com/vaadin/book-examples/blob/master/src/com/vaadin/book/examples/Description.java

**Comment by magi42** [comment]
This was fixed.
